### PR TITLE
More devices

### PR DESCRIPTION
**Pull request by obsy**
Signed-off-by: Cezary Jackiewicz <cezary@eko.one.pl>

### CODE REVIEW

**Comment by mwarning** [comment]
Thanks!

**Comment by mwarning** [comment]
hm, I think the Poray matchers are way to generic. There a lot of mismatches.

**Comment by obsy** [comment]
So... rt305x-m4 etc?

**Comment by mwarning** [comment]
I think I have to fix the matching routine.

**Comment by mwarning** [comment]
Should be fixed now. Let me know if there a negative side effects: https://github.com/freifunk-bielefeld/firmware-wizard/commit/32bc1156fbd7f8ef4dc9ebcdb59b562f371ea51a

**Pull request merged**
